language: node_js
sudo: false
node_js:
  - "8.10"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install express --save

 deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
  repo: saikatdas/RemindMeApp
  bucket: remindmeapp
  region: ap-south-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: remindmeapp
  key: latest.zip
  bundle_type: zip
  application: RemindMeApp
  deployment_group: RemindMeAppDepGrp
  region: ap-south-1
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
